int32 my_pos_x
int32 my_pos_y
int32 enemy1_x
int32 enemy1_y 
int32 enemy2_x
int32 enemy2_y
int32 ally_x
int32 ally_y
int32 goal_pos_x
int32 goal_pos_y
---
int32 next_pos_x
int32 next_pos_y
float32 degree 
bool blocked

